name: 'Print Message Action'
description: 'A simple GitHub Action that prints a custom message'
author: 'Your Name'
inputs:
  message:
    description: 'The message to print'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
